### ISSUE TITLE
[Bug]: adding a CodeNode with empty inputs/outputs crashes the render function

### ISSUE THREAD

**Issue by codemile** [Ironclad/rivet#263]
### What happened?

When working with the `CodeNode` adding an input without a name triggers a cascade of console errors that can crash the main render. Deleting the node can fix the issue or giving the input a name.

### What was the expected functionality?

Unnamed inputs/outputs should not cause any errors and be handled accordingly.

### Describe your environment

MacOS, Node 14.0.0, etc.

### Relevant log output

```shell
react-dom.development.js:86  Warning: Encountered two children with the same key, `input-`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at div
    at NodePorts (http://localhost:5173/src/components/NodePorts.tsx:47:3)
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=848ac60d:18:5)
    at NodePortsRenderer (http://localhost:5173/src/components/NodePorts.tsx:25:6)
    at http://localhost:5173/src/components/VisualNode.tsx:284:3
    at div
    at http://localhost:5173/src/components/VisualNode.tsx:39:3
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=848ac60d:18:5)
    at DraggableNode (http://localhost:5173/src/components/DraggableNode.tsx:23:3)
    at div
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-6UQ5HDQG.js?v=848ac60d:1512:49
    at DndContext2 (http://localhost:5173/node_modules/.vite/deps/chunk-632M7M3Z.js?v=848ac60d:2737:5)
    at NodeCanvas (http://localhost:5173/src/components/NodeCanvas.tsx:137:3)
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=848ac60d:18:5)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-6UQ5HDQG.js?v=848ac60d:1512:49
    at GraphBuilder (http://localhost:5173/src/components/GraphBuilder.tsx:65:29)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-6UQ5HDQG.js?v=848ac60d:1512:49
    at RivetApp (http://localhost:5173/src/components/RivetApp.tsx:63:7)
    at QueryClientProvider (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-query.js?v=848ac60d:2518:3)
    at RecoilRoot_INTERNAL (http://localhost:5173/node_modules/.vite/deps/recoil.js?v=848ac60d:2818:3)
    at RecoilRoot (http://localhost:5173/node_modules/.vite/deps/recoil.js?v=848ac60d:2936:5)

react-dom.development.js:27292  Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:27292:11)
    at scheduleUpdateOnFiber (react-dom.development.js:25475:3)
    at dispatchSetState (react-dom.development.js:17527:7)
    at useNodePortPositions.ts:122:7
    at useNodePortPositions.ts:127:5
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)
    at commitLayoutEffects_begin (react-dom.development.js:24674:7)
    at commitLayoutEffects (react-dom.development.js:24612:3)
```

### Relevant screenshots

![image](https://github.com/Ironclad/rivet/assets/50146659/d06f4175-30fe-4540-b5e5-6e8cdce72b88)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codemile** [comment]
Also crashes if the CodeNode has duplicate input names.
